#spring configuration
spring:
  codec:
    max-in-memory-size: 5MB
  output:
    ansi:
      enabled: always
  cache:
    type: redis
  data.redis:
    host: localhost
    port: 6379
logging.level:
  org.springframework.web: DEBUG
#our config
constants:
  solr:
    url: http://localhost:8983/solr/

